#!/bin/sh
# _____  _                    ___              _____  _____ __   __
#|_   _|(_) _ __   ___       |_ _| _ _        |_   _||_   _|\ \ / /
#  | |  | || '  \ / -_)       | | | ' \         | |    | |   \   / 
#  |_|  |_||_|_|_|\___|      |___||_||_|        |_|    |_|    |_|  
#

: ${XDG_CONFIG_HOME:="$HOME/.config"}
: ${TITTY_CONFIG_DIR:="$XDG_CONFIG_HOME/titty"}
CONFIG_DIR="$TITTY_CONFIG_DIR"
[ -d "$CONFIG_DIR" ] || mkdir -p "$CONFIG_DIR"
[ -f "$CONFIG_DIR/masterlist" ] || rm -f "$CONFIG_DIR/.timeison"

# Colors
pr_green="\033[1;32m"
pr_clear="\033[0m"

hms(){
	H="$(($1 / 3600))"
	M="$(($1 % 3600 / 60))"
	S="$(($1 % 60))"
	printf "%s hours, %s minutes, %s seconds" "$H" "$M" "$S"
}

tdisp(){
	IFS="|";
	case "$1" in
		'month') FMTSTRING='%m%Y';;
		'year')  FMTSTRING='%Y';;
		'week')	 FMTSTRING='%w%Y';;
		'day')	 FMTSTRING='%d%m%Y';;
		'all') ;;
		*) thelp;;


	esac
	printf "%s\n" "----------------------------------------------------------------"
	printf "%-25s\t%25s\n" "Tasks ($1)" "Logged hours"
	printf "%s\n" "----------------------------------------------------------------"
	total=0
	while read -r NAME START STOP
	do
		if [ "$1" = 'all' ] || [ "$(date --date=@"$START" +"$FMTSTRING")" -eq "$(date +"$FMTSTRING")" ]
		then
			TIME=$(("$STOP" - "$START"))
			total=$(("$total" + "$TIME"))
			printf  "%-25s\t%25s\n" "$NAME" "$(hms "$TIME")"
		fi 
	done < "$CONFIG_DIR/masterlist"
	printf "%s\n" "----------------------------------------------------------------"
	printf "%-25s\t%25s\n" "TOTAL:" "$(hms "$total")"
}


thelp(){
	printf \
"Usage:
${pr_green}titty start [taskname]${pr_clear}
	Start tracking time for a task.

${pr_green}titty start taskname [time]${pr_clear}
	Start tracking time for a task from some time ago.
	example:
	titty start Task23 1hour
	titty start Task42 1min
	titty start Task43 54sec

${pr_green}titty stop${pr_clear}
	Stop tracking the current task.

${pr_green}titty display [day|week|month|year|all]${pr_clear}
Display tracked time (default is month).

${pr_green}titty help${pr_clear}
	Display this help text.
Configuration:
	The default configuration files are located in ~/.config/titty/
	This directory can be changed using the ${pr_green}\$TITTY_CONFIG_DIR${pr_clear} environment variable.
"
exit
}

tbackstart(){
	STARTTIME="$(date -d "$(date -d "-$2")" +%s)"
	if [ ! -f "$CONFIG_DIR/.timeison" ]
	then
		printf "%s|%s" "$1" "$STARTTIME" >> "$CONFIG_DIR/masterlist"
		printf "%s\n" "Started at $(date --date=@"$STARTTIME")"
		touch "$CONFIG_DIR/.timeison"
	else
		printf "%s\n" "Time is already being tracked ya doofus!"
	fi

}

tstart(){
	STARTTIME="$(date +%s)"
	if [ ! -f "$CONFIG_DIR/.timeison" ]
	then
		if [ -z "$1" ]; then
			while [ -z "$task_name" ]; do
				printf 'Task name: '
				read -r task_name
			done
		else
			task_name="$1"
		fi
		printf "%s|%s" "$task_name" "$STARTTIME" >> "$CONFIG_DIR/masterlist"
		printf "%s\n" "Started at $(date --date=@"$STARTTIME")"
		touch "$CONFIG_DIR/.timeison"
	else
		printf "%s\n" "Time is already being tracked ya doofus!"
	fi
}

tstop(){
	if [ -f "$CONFIG_DIR/.timeison" ]
	then
		STOPTIME="$(date +%s)"
		tmp="$(mktemp)"
		tail -n1 "$CONFIG_DIR"/masterlist > "$tmp"
		IFS="|" read -r NAME STARTTIME < "$tmp"
		rm "$tmp"
		printf "%s\n" "|$STOPTIME" >> "$CONFIG_DIR/masterlist"
		TIMETAKEN=$(("$STOPTIME" - "$STARTTIME"))
		printf "%s\n" "$(hms $TIMETAKEN) tracked for $NAME"
		rm "$CONFIG_DIR/.timeison"
	else
		printf "%s\n" "You never started tracking the time, dummy!"
	fi
}

case "$1" in
	'help')
		thelp ;;
	'start')
			case "$#" in
				'1') tstart ;;
				'2') tstart "$2";;
				'3') tbackstart "$2" "$3" ;;
				*) thelp;;
			esac
	;;

	'stop')
		tstop
	;;

	'display')
			case "$#" in
				'1') tdisp 'month' ;;
				'2') tdisp "$2" ;;
				*) 	 thelp;;
			esac
	;;
	*)
		thelp;;
esac

