#!/bin/sh
# _____  _                    ___              _____  _____ __   __
#|_   _|(_) _ __   ___       |_ _| _ _        |_   _||_   _|\ \ / /
#  | |  | || '  \ / -_)       | | | ' \         | |    | |   \   / 
#  |_|  |_||_|_|_|\___|      |___||_||_|        |_|    |_|    |_|  
#

CONFIG_DIR="${TT_CONFIG_DIR:="${XDG_CONFIG_HOME:="$HOME/.config"}"}/tt"
masterlist="${TT_MASTERLIST:="$CONFIG_DIR/masterlist"}"

[ -d "$CONFIG_DIR" ] || mkdir -p "$CONFIG_DIR"

# Colors
pr_green="\033[1;32m"
pr_clear="\033[0m"

hms(){
	H="$(($1 / 3600))"
	M="$(($1 % 3600 / 60))"
	S="$(($1 % 60))"
	printf "%sh%sm%ss" "$H" "$M" "$S"
}

tcheck_tracking(){
	[ ! -s "$masterlist" ] || tail -n1 "$masterlist" | cut -d'|' -f4 | grep -q '^[0-9]\+$' 2> /dev/null
}

tdisp(){
	IFS="|";
	case "$1" in
		'month') FMTSTRING='%m%Y';;
		'year')  FMTSTRING='%Y';;
		'week')	 FMTSTRING='%w%Y';;
		'day')	 FMTSTRING='%d%m%Y';;
		'all') ;;
		*) thelp;;


	esac
	if [ -s "$masterlist" ]; then
	printf "%s\n" "-----------------------------------------------------------------------------------------"
	printf "%-25s\t%25s%25s\n" "Tasks ($1)" "Logged hours" "INCOME"
	printf "%s\n" "-----------------------------------------------------------------------------------------"
	total=0
	total_income=0
	while read -r NAME START RATE STOP
	do
		if [ "$1" = 'all' ] || [ "$(date -j -f "%s" "$START" +"$FMTSTRING")" -eq "$(date +"$FMTSTRING")" ]
		then
			TIME=$((STOP - START))
			total=$((total + TIME))
			TIME_IN_HOURS=$(echo "scale=2; $TIME / 3600" | bc)
			income=$(echo "$TIME_IN_HOURS * $RATE" | bc)
			total_income=$(echo "scale=2; $total_income + $income" | bc)
			printf  "%-25s\t%25s%25s\n" "$NAME" "$(hms "$TIME")" "$income"
		fi 
	done < "$masterlist"
	printf "%s\n" "-----------------------------------------------------------------------------------------"
	printf "%-25s\t%25s%25s\n" "TOTAL:" "$(hms "$total")" "$total_income"
	else
		printf 'No completed tasks to display\n'
	fi
}


thelp(){
	printf \
"Usage:
${pr_green}tt start [taskname]${pr_clear}
	Start tracking time for a task.

${pr_green}tt start taskname [time]${pr_clear}
	Start tracking time for a task from some time ago.
	example:
	tt start Task23 1hour
	tt start Task42 1min
	tt start Task43 54sec

${pr_green}tt status${pr_clear}
	Display the time tracked so far for the current task.

${pr_green}tt raw${pr_clear}
	Display the raw masterlist (for piping into other programs)

${pr_green}tt stop${pr_clear}
	Stop tracking the current task.

${pr_green}tt display [day|week|month|year|all]${pr_clear}
	Display tracked time (default is month).

${pr_green}tt delete [all]${pr_clear}
	Delete the previous task or all tasks.

${pr_green}tt help${pr_clear}
	Display this help text.
Configuration:
	The default configuration files are located in ~/.config/tt/
	This directory can be changed using the ${pr_green}\$TT_CONFIG_DIR${pr_clear} environment variable.
"
exit
}

tbackstart(){
	STARTTIME="$(date -j -f "%Y-%m-%d %H:%M:%S" "$(date -d "-$2" +"%Y-%m-%d %H:%M:%S")" +%s)"
	if tcheck_tracking
	then
		printf "%s|%s" "$1" "$STARTTIME" >> "$masterlist"
		printf "%s\n" "Started at $(date -j -f "%s" "$STARTTIME")"
	else
		printf "%s\n" "Time is already being tracked ya doofus!"
	fi

}

tstart(){
	STARTTIME="$(date +%s)"
	if tcheck_tracking
	then
		if [ -z "$1" ]; then
			while [ -z "$task_name" ]; do
				printf 'Task name: '
				read -r task_name
				printf 'Rate($/hour) - only enter the number: '
				read -r rate
			done
		else
			task_name="$1"
			printf 'Rate($/hour) - only enter the number: '
			read -r rate
		fi
		printf "%s|%s|%s" "$task_name - $(date --iso)" "$STARTTIME" "$rate" >> "$masterlist"
		printf "%s\n" "Started at $(date -j -f "%s" "$STARTTIME") for $rate per hour"
	else
		printf "%s\n" "Time is already being tracked ya doofus!"
	fi
}

tstop(){
	if ! tcheck_tracking
	then
		STOPTIME="$(date +%s)"
		tmp="$(mktemp)"
		tail -n1 "$CONFIG_DIR"/masterlist > "$tmp"
		IFS="|" read -r NAME STARTTIME < "$tmp"
		rm "$tmp"
		printf "%s\n" "|$STOPTIME" >> "$masterlist"
		TIMETAKEN=$(($STOPTIME - $STARTTIME))
		printf "%s\n" "Stopped - $(hms $TIMETAKEN) tracked for $NAME"
	else
		printf "%s\n" "You never started tracking the time, dummy!"
	fi
}

traw(){
	cat $masterlist 
}

tstatus(){
	if ! tcheck_tracking
	then
		CURRENT_TIME="$(date +%s)"
		tmp="$(mktemp)"
		tail -n1 "$CONFIG_DIR"/masterlist > "$tmp"
		IFS="|" read -r NAME STARTTIME < "$tmp"
		rm "$tmp"
		TIMETAKEN=$(($CURRENT_TIME - $STARTTIME))
		printf "%s\n" "$(hms $TIMETAKEN) tracked for $NAME"
	else
		printf "%s\n" "You never started tracking the time, dummy!"
	fi
}

tdelete(){
	if [ -s "$masterlist" ]; then
		case "$1" in
			'all')
				: > "$masterlist"
				printf 'Deleted all tasks\n'
				;;
			*)
				printf 'Deleted '
				tail -n1 "$masterlist" | cut -d'|' -f1
				sed -i '$d' "$masterlist"
				;;
		esac
	else
		printf '%s\n' 'No tasks to delete'
	fi
	exit
}

tsearch(){
    if [ -z "$1" ]; then
        printf 'Search term: '
        read -r search_term
    else
        search_term="$1"
    fi
    printf "%s\n" "-----------------------------------------------------------------------------------------"
    printf "%-25s\t%25s%25s\n" "Tasks" "Logged hours" "INCOME"
    printf "%s\n" "-----------------------------------------------------------------------------------------"
    total=0
    total_income=0
    while IFS="|" read -r NAME START RATE STOP
    do
        if echo "$NAME" | grep -iq "$search_term"
        then
            TIME=$((STOP - START))
            total=$((total + TIME))
            TIME_IN_HOURS=$(echo "scale=2; $TIME / 3600" | bc)
            income=$(echo "$TIME_IN_HOURS * $RATE" | bc)
            total_income=$(echo "scale=2; $total_income + $income" | bc)
            printf  "%-25s\t%25s%25s\n" "$NAME" "$(hms "$TIME")" "$income"
        fi 
    done < "$masterlist"
    printf "%s\n" "-----------------------------------------------------------------------------------------"
    printf "%-25s\t%25s%25s\n" "TOTAL:" "$(hms "$total")" "$total_income"
}


case "$1" in
	'search')
        tsearch "$2"
    ;;
	'start')
			case "$#" in
				'1') tstart ;;
				'2') tstart "$2";;
				'3') tbackstart "$2" "$3" ;;
				 *) thelp;;
			esac
	;;

	'stop')
		tstop
	;;

	'help')
		thelp
	;;

	'delete')
		tdelete "$2"
	;;

	'display')
			case "$#" in
				'1') tdisp 'month' ;;
				'2') tdisp "$2" ;;
				*) 	 thelp;;
			esac
	;;
	'status')
		tstatus;;
	'raw')
		traw;;
	*)
		thelp;;
esac

